src/main/java/it/smartcommunitylab/aac/config/OAuth2SecurityConfig.java, src/main/java/it/smartcommunitylab/aac/oauth/OAuth2TokenServices.java, src/main/java/it/smartcommunitylab/aac/oauth/auth/ClientBasicAuthFilter.java, src/main/java/it/smartcommunitylab/aac/oauth/auth/ClientFormAuthTokenEndpointFilter.java, src/main/java/it/smartcommunitylab/aac/oauth/auth/OAuth2ClientRefreshAuthenticationProvider.java, src/main/java/it/smartcommunitylab/aac/oauth/auth/OAuth2ClientRefreshAuthenticationToken.java, src/main/java/it/smartcommunitylab/aac/oauth/client/OAuth2Client.java, src/main/java/it/smartcommunitylab/aac/oauth/client/OAuth2ClientAdditionalConfig.java, src/main/java/it/smartcommunitylab/aac/oauth/client/OAuth2ClientConfigMap.java, src/main/java/it/smartcommunitylab/aac/oauth/client/OAuth2ClientInfo.java, src/main/java/it/smartcommunitylab/aac/oauth/model/OAuth2ClientDetails.java, src/main/java/it/smartcommunitylab/aac/oauth/persistence/OAuth2ClientEntity.java, src/main/java/it/smartcommunitylab/aac/oauth/service/OAuth2ClientDetailsService.java, src/main/resources/public/html/app/conf.oauth2.html
Add refresh token rotation and support requesting refresh via token endpoint without using a client secret.
Supports the following flow:
1. enable refresh token rotation for client
1. request an access_token with `offline_access` scope via `authorization_code` and PKCE
1. obtain a refresh token bound to PKCE auth
1. refresh access token via refresh token request without secret
=> Refresh token rotation

src/main/resources/public/js/realmapps.js
fixed SuperAdmin capability to assign roles/authorities to client applications
=> fix #330: SuperAdmin can now assign roles/authorities to client applications

src/main/java/it/smartcommunitylab/aac/oauth/auth/ClientSecretBasicAuthenticationConverter.java
When attempting conversion, ClientSecretBasicAuthenticationConverter should not throw an exception when no Authorization header is found, but should return null so that the next Authentication Converter (ClientSecretPostAuthenticationConverter) can attempt the conversion
=> fix #335: update client secret basic auth converter to not throw exception when attempting conversion

src/main/resources/public/html/app/audit.html, src/main/resources/public/html/realm.audit.html, src/main/resources/public/html/realm.dashboard.html, src/main/resources/public/html/user/audit.html
fixed audit timestamp conversion which was preventing the display of the "Time" field in the Audit and Dashboard pages and in the User and Client Audit tabs
=> fix #209: audit timestamp visualization has been restored

src/main/java/it/smartcommunitylab/aac/openid/endpoint/EndSessionEndpoint.java
according to #378 the hidden URL must be END_SESSION_CONFIRM_URL, however in #395 have overridden the method in END_SESSION_URL.
That fix the problem establishing the correct URL END_SESSION_CONFIRM_URL
=> fix endsession URL, the previous was not reachable

src/main/java/it/smartcommunitylab/aac/oauth/request/OAuth2RequestValidator.java
Add validation for missing redirect uri when scope contains openid
=> fix #409: add validation for missing redirect uri with openid scope

src/main/resources/public/html/provider/idp.conf.saml.html
Now it is possible to persist Login Service Location value in the SAML Idp Configuration
=> fix #432: persist Login Service Location value from the dev console

src/main/java/it/smartcommunitylab/aac/oauth/flow/WebhookOAuthFlowExtensions.java
fix #436: register time module to object mapper for serialization
Register Java Time Module when defining object mapper to allow User to be correctly serialized
=> backport #441 to 4.x

src/main/java/it/smartcommunitylab/aac/oauth/flow/WebhookOAuthFlowExtensions.java
Register Java Time Module when defining object mapper to allow User to be correctly serialized
=> fix #436: register time module to object mapper for serialization

src/main/java/it/smartcommunitylab/aac/config/OAuth2UserSecurityConfig.java, src/main/java/it/smartcommunitylab/aac/config/SecurityConfig.java
add ignore path for CSRF for:
"/endsession"
"/oauth/authorize"
to permit POST request as specifics OIDC
=> 5.x.OIDC fix post endsession and authorize

src/main/resources/public/html/provider/ap.attributesets.html, src/main/resources/public/html/provider/ap.settings.html, src/main/resources/public/js/realmproviders.js
console can now save and load attribute providers settings (audit, persistence, attribute sets)
=> fix #451 console can save and load attribute providers settings

src/main/java/it/smartcommunitylab/aac/saml/provider/SamlAuthenticationProvider.java, src/main/java/it/smartcommunitylab/aac/saml/provider/SamlIdentityProviderConfig.java, src/main/java/it/smartcommunitylab/aac/saml/provider/SamlIdentityProviderConfigMap.java, src/main/resources/public/html/provider/idp.conf.saml.html
This is a proposal resolution for issue #311 .
Added option to use the value in a custom SAML attribute as subject identifier when performing a SAML authentication.
The default behaviour (still supported when no attribute is choosen) uses a nonce/random value obtained from the SAML and will result in a new account at each user athentication.
=> Bugfix SAML new accounts

src/main/java/it/smartcommunitylab/aac/saml/provider/SamlAttributeProvider.java
claims family_name is always overwritten by surname from account, even when it dows not exists, possibly deleting a valid family name attribute already existing
=> claims family_name is overwritten only if surname exists

src/main/resources/db/sql/oauth2/schema-postgresql.sql
Added ad index to a selected table in the PostgreSQL as a mitigation to issue #496.
The transaction described in the issue at isolation level serializable locks the whole table. Allegedly, adding an index will lock fewer rows, reducing the probability of the described error.
=> add index to postgresql schema

src/main/java/it/smartcommunitylab/aac/repository/SafeString.java, src/main/java/it/smartcommunitylab/aac/repository/SafeStringCollectionValidator.java, src/main/java/it/smartcommunitylab/aac/repository/SafeStringMapValidator.java, src/main/java/it/smartcommunitylab/aac/repository/SafeStringValidator.java
Added an annotation reserved for security-based validation of user provided strings, as emerged from the following discussion
https://github.com/scc-digitalhub/AAC/pull/506#issuecomment-1905580717
The annotation is unused in the current pull request, but might be used for any user provided string that are rendered in a console page such as the one described in enhancement #505
Currently, the only sanitization mode supported are the ones provided by the jsoup library, but theorically more modes or flags can be defined if necessary.
=> added safestring annotation

src/main/java/it/smartcommunitylab/aac/oauth/store/jdbc/AutoJdbcAuthorizationCodeServices.java
When removing an aouth code and returning a token, the code service might return a token even if the code deletion fails.
Changed the service to return a token only if the code service succesfully removes the code.
This is a fix for the bug described in Issue #511
=> bugfix double code return

src/main/resources/templates/login/button-cie.html, src/main/resources/templates/login/button-expand.html, src/main/resources/templates/login/button.html
Added custom css class value to the buttons in the login page, in particolare to the:
1. the icon/logo region of the used identity provider
2. the text/title region of the used identity provider
The two css class above are meant to simplify the button customization process through the realm css page.
=> simplified customization

src/main/java/it/smartcommunitylab/aac/saml/provider/SamlAuthenticationProvider.java
Proposed solution to Issue #463 
ACR is extracted from Saml assertion and, if found, is included as a custom named attribute in the principal.
Example Saml contaning an ACR in an assertion below
`  0 <saml2p:Response Destination="destination-URI"`
`  1                  ID="removed"`
`  2                  InResponseTo=""`
`  3                  IssueInstant="2024-01-19T10:15:49.678Z"`
`  4                  Version="2.0"`
`  5                  xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol"`
`  6                  xmlns:xs="http://www.w3.org/2001/XMLSchema"`
`  7                  >`
`  8     <saml2:Issuer xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion">issuer-URI</saml2:Issuer>`
`  9     <ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">`
` 10         REMOVED_FOR_BREVITY`
` …
=> added saml acr assertion into auth context

src/main/java/it/smartcommunitylab/aac/attributes/provider/AttributeProviderSettingsMap.java, src/main/java/it/smartcommunitylab/aac/identity/provider/IdentityProviderSettingsMap.java, src/main/resources/public/html/provider/ap.settings.html, src/main/resources/public/html/provider/idp.settings.html, src/main/resources/public/js/realmproviders.js
Proposal for enchancement #505 
A new field reserved for internal notes was included in the settings map of identity providers and attribute providers.
The notes value is provided by the user and is used in the rendering of the given provider console page. The new safestring annotation was adopted for sanitization purposes (in that unsafe values throw an error). Proper value manipulation to a safe string will eventually be conidered in a future proposal.
=> Proposal for enchancement #505

src/main/java/it/smartcommunitylab/aac/core/UserDetails.java, src/main/java/it/smartcommunitylab/aac/model/User.java
Changed behaviour when extracting claims in order to satisfy a `/userinfo` request. Now claims are no longer extracted from an undefined user account, as the primary source of the claims is the "first" identity of that user, where before identity ordering was not guaranteed.
=> fix: changed userinfo behaviour #544

src/main/java/it/smartcommunitylab/aac/claims/LocalGraalExecutionService.java, src/main/java/it/smartcommunitylab/aac/config/ExecutionConfig.java, src/main/resources/application.yml, src/test/java/it/smartcommunitylab/aac/claims/TestGraalExecutionService.java
Added new config so that it can be decided wether a comments are stripped from script (of identity providers and attribute providers) before execuition.
Default configuration is that comments are stripped from scripts (security-by-default).
=> fix: new config to support #547

src/main/java/it/smartcommunitylab/aac/identity/service/IdentityProviderService.java
Temporary solution to issue #551 
Added current timestamp as version for configurable identity provider fior usage with configuration `persistence.repository.providerConfig=jdbc` .
Note that this workaround techically conflict with the design choice of having immutable providers defined in the config file. The providers are _still_ intended to be immutable.
=> added timestamp as version to custom idp from app.yml

src/main/java/it/smartcommunitylab/aac/spid/provider/SpidIdentityProviderConfigMap.java
As a provisional solution to issue https://github.com/scc-digitalhub/AAC/issues/592 , satefy annotation from `SpidIdentityProviderConfigMap` are removed.
=> fix: removed spid annotation #592

dev-console/src/i18n/en/fields.json, dev-console/src/idps/schemas.ts, src/main/java/it/smartcommunitylab/aac/openidfed/provider/OpenIdFedIdentityProviderConfigMap.java, src/main/java/it/smartcommunitylab/aac/openidfed/service/DefaultOpenIdRpMetadataResolver.java, src/main/resources/public/html/provider/idp.conf.openidfed.html
This pull request closes #602
Added configuration for openid federation metadata extensions `logo_uri`, `policy_uri`, `homepage_uri`.
The parameters are optionals. When not set, the previuous parameters resolution logic is used.
This is done to preserve backward compatibility.
@matteo-s this is my first PR in a while and I'm not fully aware of all previous changes. Please double (or triple) check that nothing silly was done.
=> feat: config openidfed metadata extension
